language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
services:
  - docker
branches:
  only:
  - master
before_install:
  - chmod +x release.sh
  - chmod +x build.sh
script: ./release.sh